mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1        #逻辑删除配置
      logic-not-delete-value: 0
  configuration:                  # 原生配置
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    call-setters-on-nulls: false  # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段

spring:
  datasource:
    url: jdbc:mysql://${sdk.datasource.ip}:${sdk.datasource.port}/${sdk.datasource.database}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: ${sdk.datasource.username}
    password: ${sdk.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
