mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.saidake.paizhi.model     #实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config:
      id-type: auto

sdk:
  datasource:
    ip: localhost
    username: root
    password: root
    port: 3306
    database: bluetooth-app
