spring:
  profiles:
    active: dev
springdoc:
  swagger-ui:
    doc-expansion: none
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
#=============================================================================================================== 文件
qihuo:
  simulate:
    account-info-path: D:\Desktop\OneDrive\STOCK.xlsx
  day:
    sr: ${BASEDIR}\assets\day\28#SR2305.day
fuhui:
  account-info-path: C:\Users\saidake\AppData\Local\Temp\FxtsReportsTmp  # 获取福汇导出的账号交易数据 目录
server:
  port: 48124
