sdk:
  generator:
    operation-type: overwrite     # 覆盖
    project-root-path: D:\Desktop\DevProject\mybatis-plus-template
    template:
      table-comment: sdkTableComment
      table-name: sdk_template
    core:
      service-package: com.simi.service
      controller-package: com.simi.com.simi.citi.controller
      mapper-package: com.simi.mybatis.mapper
      mapper-resources-folder: mapper

      entity-package: com.simi.mybatis.entity

      dto-request-package: com.simi.model.request
      dto-response-package: com.simi.model.response
    io:
      has-dto-table-folder: true
      has-service-table-folder: false
      has-controller-table-folder: false
      has-mapper-resources-table-folder: false
    suffix:
      service-suffix: Service
      service-impl-suffix: ServiceImpl
      controller-suffix: Controller
      mapper-suffix: Mapper
      mapper-resources-suffix: Mapper

      entity-suffix: Entity

      dto-add-request-suffix: AddRequest
      dto-update-request-suffix: UpdateRequest


      dto-request-suffix: Request
      dto-response-suffix: Response

      method-suffix: Handler
    db:
      pass-fields: id,create_time,update_time  # entity跳过的字段
      #      pass-tables: t_user_bicycle_name        # 跳过的表，   配置后generate-tables会不生效
      generate-tables: t_user,t_user_share     # 必须生成的表，配置后pass-tables会不生效
    services:
      - table: sdk_template
        add-handler:
          request-pass-fields: age  # add request 跳过的字段（继承entity跳过的字段）
      - table: t_user
        add-handler:
          request-pass-fields: del,last_login_time  # add request 跳过的字段（继承entity跳过的字段）
        special:
          - method: post
            name: login,登录
            request:
              - info: userPhone,手机号,String,required
                check: t_user,user_phone
