[libraries]
spring-boot-bom = { group = "org.springframework.boot", name = "spring-boot-dependencies", version = "3.0.5" }
spring-cloud-bom = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version = "2022.0.2" }
