#=============================================================================================== Log
#simi:
#  log-path: ${PROJECT_PATH}/AAAlogs
logging:
  config: classpath:logback-simi.xml      #指定logback日志文件（默认logback-spring.xml）
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: debug
