spring:
  profiles:
    active: dev


#=============================================================================================================== 文件
day:
  sr: ${BASEDIR}\assets\day\28#SR2305.day