spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                  # 请求路径前可以添加微服务名称（不带也可以）   // http://nacos-provider/test   -->    http://localhost:8001/test
          lower-case-service-id: true    # 将请求路径上的服务名配置为小写
      routes:
        - id: bluetooth-app
          uri: http://sdk.vin:48123
          predicates:
            - Path=/api-bluetooth/**
          filters:
            - StripPrefix=1
        - id: sdk-mybatis-plus
          uri: lb://sdk-mybatis-plus
          predicates:
            - Path=/api-mybatis-plus/**
          filters:
            - StripPrefix=1
        - id: generator
          uri: lb://sdk-generator
          predicates:
            - Path=/api-generator/**
          filters:
            - StripPrefix=1

sdk:
  swagger-agg:
#    generate-routes: generator,sdk-mybatis-plus
    generate-routes: generator,sdk-mybatis-plus,bluetooth-app
