import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class MainTest {

    /**
     * Summary (generated by saidake-manage-project):
     *     testContent11111
     *         testContent11111
     * @param	args
     * @return
     */
    public static void main(String[] args) {
        //1. testContent11111
        //=============================================================================================== 测试样本
        String testString="abcdefg12345";
        String testPatternString="   //1. abcd";
        //2. testContent11111
        //=============================================================================================== 实验区
        Pattern compile = Pattern.compile("^\\s*//[1-9]\\.\\s.*?");
        String str = testPatternString.replaceAll("^\\s*//[1-9]\\.\\s.*?", "");
        Matcher matcher = compile.matcher(testPatternString);
        if(compile.matcher(testPatternString).find()){
            String group = matcher.group(0);
            System.out.println(group.replaceAll("[^1-9]",""));
        }
        System.out.println(str);
    }

    private String lala(Integer a, String b){
        return null;
    }

}
